Data Structures in Pandas:--

Pandas provides two data structures for manipulating data which are as follows:

1. Pandas Series:--
A Pandas Series is a one-dimensional labeled array capable of holding data of any type. It can be created from Python lists, NumPy arrays, dictionaries, scalar values or data loaded from external sources such as CSV files, Excel files and databases. The labels associated with a Series are called its index.

In [8]:

import numpy as np;
import pandas as pd;

marks = pd.Series([85, 90, 78, 92])

# print(marks)
marks

0    85
1    90
2    78
3    92
dtype: int64

2. Pandas DataFrame is a two-dimensional data structure with labeled axes (rows and columns). It is created by loading the datasets from existing storage which can be a SQL database, a CSV file or an Excel file. It can be created from lists, dictionaries, a list of dictionaries etc.

In [9]:
import numpy as np;
import pandas as pd;

In [ ]:
data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 42],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]
}

df = pd.DataFrame(data)

In [ ]:
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [10]:
data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 42],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]
}

df = pd.DataFrame(data)

In [ ]:
df

   Age      City  Salary
0   28  New York   65000
1   34     Paris   70000
2   29    Berlin   62000
3   42    London   85000

In [12]:
data = {
  'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 42],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]
}
df2 =pd.DataFrame(data)
rows =   ['John', 'Anna', 'Peter', 'Linda']
df2 = pd.DataFrame(data, index=rows);
df2

        Name  Age      City  Salary
John    John   28  New York   65000
Anna    Anna   34     Paris   70000
Peter  Peter   29    Berlin   62000
Linda  Linda   42    London   85000

## Selecting and indexing of coloumns

In [ ]:
df2[["Name","City"]]

        Name      City
John    John  New York
Anna    Anna     Paris
Peter  Peter    Berlin
Linda  Linda    London

In [ ]:
df2["Name"]

John      John
Anna      Anna
Peter    Peter
Linda    Linda
Name: Name, dtype: str

## Creating New Coloumn

In [ ]:
df2["Designation"] =["doctor","Enginear","Doctor","Lawer"];

In [ ]:
df2

        Name  Age      City  Salary Designation
John    John   28  New York   65000      doctor
Anna    Anna   34     Paris   70000    Enginear
Peter  Peter   29    Berlin   62000      Doctor
Linda  Linda   42    London   85000       Lawer

##  Removing Coloumn

In [ ]:
df2.drop('Designation',axis=1)

        Name  Age      City  Salary
John    John   28  New York   65000
Anna    Anna   34     Paris   70000
Peter  Peter   29    Berlin   62000
Linda  Linda   42    London   85000

In [ ]:
df2.drop('Designation',axis=1,inplace=True)

In [ ]:
df2

        Name  Age      City  Salary
John    John   28  New York   65000
Anna    Anna   34     Paris   70000
Peter  Peter   29    Berlin   62000
Linda  Linda   42    London   85000

In [ ]:
df2.drop(["City","Salary"],axis=1)

        Name  Age
John    John   28
Anna    Anna   34
Peter  Peter   29
Linda  Linda   42

In [ ]:
df2.drop("John",axis=0)

        Name  Age    City  Salary
Anna    Anna   34   Paris   70000
Peter  Peter   29  Berlin   62000
Linda  Linda   42  London   85000

## Selecting Rows

In [ ]:
df.loc[[0,1]]

   Name  Age      City  Salary
0  John   28  New York   65000
1  Anna   34     Paris   70000

## Selecting subsets of Rows and Coloumns

In [ ]:
df.loc[[0,1]][["City","Salary"]]

       City  Salary
0  New York   65000
1     Paris   70000

In [ ]:
df.loc[[2,3]][["Name","Age"]]

    Name  Age
2  Peter   29
3  Linda   42

## Conditional Selection

In [ ]:
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

I only want to see those people whose age is above 30

In [ ]:
df[df["Age"]>30]

    Name  Age    City  Salary
1   Anna   34   Paris   70000
3  Linda   42  London   85000

I only want people whose age is above 30 and their city is must be paris

In [ ]:
df[(df["Age"]>30) & (df["City"] == "Paris")]

   Name  Age   City  Salary
1  Anna   34  Paris   70000