## Finding missing Data

In [2]:
import numpy as np ;
import pandas as pd;

In [3]:
data = {
    'A': [1, 2, 3, 4, 5],
    'B': [1, 2, 3, 4, 5],
    'C': [1, 2, 3, np.nan, np.nan],
    'D': [1, np.nan, np.nan, np.nan, 5]
}

df = pd.DataFrame(data)

df

   A  B    C    D
0  1  1  1.0  1.0
1  2  2  2.0  NaN
2  3  3  3.0  NaN
3  4  4  NaN  NaN
4  5  5  NaN  5.0

In [4]:
df.isna()

       A      B      C      D
0  False  False  False  False
1  False  False  False   True
2  False  False  False   True
3  False  False   True   True
4  False  False   True  False

In [9]:
df.isna().sum()

A    1
B    1
C    2
D    3
dtype: int64

In [ ]:
# checking for any null value is availabe

df.isna().any()

A    True
B    True
C    True
D    True
dtype: bool

Removing the missing data

In [17]:
df

   A  B    C    D
0  1  1  1.0  1.0
1  2  2  2.0  NaN
2  3  3  3.0  NaN
3  4  4  NaN  NaN
4  5  5  NaN  5.0

In [ ]:
# rows wise drop hoga
df.dropna()

   A  B    C    D
0  1  1  1.0  1.0

In [ ]:

# thresh =3 means Jis row mein kam se kam 3 non-null (non-NaN) values hain, us row ko rakho.

df.dropna(thresh=3)

   A  B    C    D
0  1  1  1.0  1.0
1  2  2  2.0  NaN
2  3  3  3.0  NaN
4  5  5  NaN  5.0

 Filling the missing datam

In [23]:
df

   A  B    C    D
0  1  1  1.0  1.0
1  2  2  2.0  NaN
2  3  3  3.0  NaN
3  4  4  NaN  NaN
4  5  5  NaN  5.0

In [25]:
# ye sab jitne bhi changes ho rhe he wo real table me nii ho rha he uske liye inplace = True likhna padega.

df.fillna(0)

   A  B    C    D
0  1  1  1.0  1.0
1  2  2  2.0  0.0
2  3  3  3.0  0.0
3  4  4  0.0  0.0
4  5  5  0.0  5.0

In [5]:
# agr hame alg alg coloumn me different values dena ho to :--
#colounms wise hoga

values ={'A':0,'B':100,'C':300,'D':400}
df.fillna(value=values)

   A  B      C      D
0  1  1    1.0    1.0
1  2  2    2.0  400.0
2  3  3    3.0  400.0
3  4  4  300.0  400.0
4  5  5  300.0    5.0

In [29]:
# ab yaha par mean se data fill hoga
df.fillna(df.mean());
df

   A  B    C    D
0  1  1  1.0  1.0
1  2  2  2.0  NaN
2  3  3  3.0  NaN
3  4  4  NaN  NaN
4  5  5  NaN  5.0