In [ ]:
import numpy as np;
import pandas as pd;

In [5]:
employees = pd.DataFrame({
    'employee_id': [1, 2, 3, 4, 5],
    'name': ['John', 'Anna', 'Peter', 'Linda', 'Bob'],
    'department': ['HR', 'IT', 'Finance', 'IT', 'HR']
})

# DataFrame 2: Salary information
salaries = pd.DataFrame({
    'employee_id': [1, 2, 3, 6, 7],
    'salary': [60000, 80000, 65000, 70000, 90000],
    'bonus': [5000, 10000, 7000, 8000, 12000]
})

In [6]:
employees

   employee_id   name department
0            1   John         HR
1            2   Anna         IT
2            3  Peter    Finance
3            4  Linda         IT
4            5    Bob         HR

In [7]:
salaries

   employee_id  salary  bonus
0            1   60000   5000
1            2   80000  10000
2            3   65000   7000
3            6   70000   8000
4            7   90000  12000

Now we going to merge these two tables on the basis of different ways :--

In [8]:
pd.merge(employees ,salaries)

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000

In [9]:
# here employee_id is showing on which basing these two table should be merged

pd.merge(employees,salaries, on="employee_id")

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000

In [10]:
#  Dono DataFrames mein jo matching rows/common values hain, sirf unko rakho.

# Pandas yahan automatically common column employee_id ko matching ke liye use karega. 

pd.merge(employees ,salaries , how="inner")

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000

In [11]:
# how="outer" dono DataFrames ke saare rows ko include karta hai.
# Jahan matching data nahi hota, wahan NaN aa jata hai.

pd.merge(employees,salaries,how="outer")

   employee_id   name department   salary    bonus
0            1   John         HR  60000.0   5000.0
1            2   Anna         IT  80000.0  10000.0
2            3  Peter    Finance  65000.0   7000.0
3            4  Linda         IT      NaN      NaN
4            5    Bob         HR      NaN      NaN
5            6    NaN        NaN  70000.0   8000.0
6            7    NaN        NaN  90000.0  12000.0

In [12]:
# how = "left" means yaha par (employees and salaries) me se employee ko priority milege kyunki wo left me he .

pd.merge(employees,salaries,how="left")

   employee_id   name department   salary    bonus
0            1   John         HR  60000.0   5000.0
1            2   Anna         IT  80000.0  10000.0
2            3  Peter    Finance  65000.0   7000.0
3            4  Linda         IT      NaN      NaN
4            5    Bob         HR      NaN      NaN

In [14]:
# how = "right" means yaha par (employees and salaries) me se salaries ko priority milege kyunki wo right me he .

pd.merge(employees,salaries,how="right")

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000
3            6    NaN        NaN   70000   8000
4            7    NaN        NaN   90000  12000

### Concatination

In [16]:
df1 =pd.DataFrame({

    'A':[ "A0","B0","C0"],
    'B':[ "A1","B1","C1"],
    'C':[ "A2","B2","C2"]
    
    


})

df2 =pd.DataFrame({
    'A':[ "A3","B3","C3"],
    'B':[ "A4","B4","C4"],
    'C':[ "A5","B5","C5"]
})

In [18]:
df1

    A   B   C
0  A0  A1  A2
1  B0  B1  B2
2  C0  C1  C2

In [20]:
df2

    A   B   C
0  A3  A4  A5
1  B3  B4  B5
2  C3  C4  C5

In [23]:
pd.concat([df1,df2])

    A   B   C
0  A0  A1  A2
1  B0  B1  B2
2  C0  C1  C2
0  A3  A4  A5
1  B3  B4  B5
2  C3  C4  C5

In [25]:
pd.concat([df1,df2],axis=1)

    A   B   C   A   B   C
0  A0  A1  A2  A3  A4  A5
1  B0  B1  B2  B3  B4  B5
2  C0  C1  C2  C3  C4  C5

### Joining two dataFrames

In [27]:
df1 = pd.DataFrame({
    'name:': ['Alice' ,'bob','charlie']
}, index= [1,2,3])

df2 = pd.DataFrame({
    'Score' : [85,90,75]
},index=[2,3,4])

In [29]:
df1

     name:
1    Alice
2      bob
3  charlie

In [31]:
df2

   Score
2     85
3     90
4     75

In [33]:
df1.join(df2)

     name:  Score
1    Alice    NaN
2      bob   85.0
3  charlie   90.0

In [34]:
df1.join(df2,how='outer')

     name:  Score
1    Alice    NaN
2      bob   85.0
3  charlie   90.0
4      NaN   75.0